#pragma once
#include <string>
#include <fstream>
#include <iostream>
#include "pokemon.h"
#include <sstream>
#include <vector>
#include "pokemon.h"
#include <stdlib.h>
#include <windows.h>
#include "type.h"
#include "info.h"

using namespace std;

vector<pokemon> pokemon::pokedex;
vector<info> pokemon::dbdex;

bool pokemon::hasIvs()
{
	return  (this->ivatk + this->ivdef + this->ivats + this->ivdes + this->ivpv + this->ivspd) > 0 ? true : false;
}

bool pokemon::hasEvs()
{
	return  (this->evatk + this->evdef + this->evats + this->evdes + this->evpv + this->evspd) > 0 ? true : false;
}

string pokemon::toString()
{
	string fnord;
	fnord = to_string(this->id);
	fnord += "-";
	fnord += to_string(this->level);
	fnord += "-";
	fnord += to_string(this->pv);
	fnord += "-";
	fnord += to_string(this->atk);
	fnord += "-";
	fnord += to_string(this->def);
	fnord += "-";
	fnord += to_string(this->ats);
	fnord += "-";
	fnord += to_string(this->des);
	fnord += "-";
	fnord += to_string(this->spd);
	fnord += "-";
	fnord += to_string(this->ivpv);
	fnord += "-";
	fnord += to_string(this->ivatk);
	fnord += "-";
	fnord += to_string(this->ivdef);
	fnord += "-";
	fnord += to_string(this->ivats);
	fnord += "-";
	fnord += to_string(this->ivdes);
	fnord += "-";
	fnord += to_string(this->ivspd);
	fnord += "-";
	fnord += to_string(this->evpv);
	fnord += "-";
	fnord += to_string(this->evatk);
	fnord += "-";
	fnord += to_string(this->evdef);
	fnord += "-";
	fnord += to_string(this->evats);
	fnord += "-";
	fnord += to_string(this->evdes);
	fnord += "-";
	fnord += to_string(this->evspd);
	fnord += "-";
	fnord += to_string((int)this->type1);
	fnord += "-";
	fnord += to_string((int)this->type2);
	fnord += "-";
	fnord += to_string((int)this->nature1);
	return fnord;
}

void pokemon::fromString(string fnord)
{
	string foo = fnord;
	int found = foo.find("-");
	string x = foo.substr(0, found);
	this->id = stoi(x);
	foo.erase(0, found + 1);
	found = foo.find("-");
	x = foo.substr(0, found);
	this->level = stoi(x);
	foo.erase(0, found + 1);
	found = foo.find("-");
	x = foo.substr(0, found);
	this->pv = stoi(x);
	foo.erase(0, found + 1);
	found = foo.find("-");
	x = foo.substr(0, found);
	this->atk = stoi(x);
	foo.erase(0, found + 1);
	found = foo.find("-");
	x = foo.substr(0, found);
	this->def = stoi(x);
	foo.erase(0, found + 1);
	found = foo.find("-");
	x = foo.substr(0, found);
	this->ats = stoi(x);
	foo.erase(0, found + 1);
	found = foo.find("-");
	x = foo.substr(0, found);
	this->des = stoi(x);
	foo.erase(0, found + 1);
	found = foo.find("-");
	x = foo.substr(0, found);
	this->spd = stoi(x);
	foo.erase(0, found + 1);
	found = foo.find("-");
	x = foo.substr(0, found);
	this->ivpv = stoi(x);
	foo.erase(0, found + 1);
	found = foo.find("-");
	x = foo.substr(0, found);
	this->ivatk = stoi(x);
	foo.erase(0, found + 1);
	found = foo.find("-");
	x = foo.substr(0, found);
	this->ivdef = stoi(x);
	foo.erase(0, found + 1);
	found = foo.find("-");
	x = foo.substr(0, found);
	this->ivats = stoi(x);
	foo.erase(0, found + 1);
	found = foo.find("-");
	x = foo.substr(0, found);
	this->ivdes = stoi(x);
	foo.erase(0, found + 1);
	found = foo.find("-");
	x = foo.substr(0, found);
	this->ivspd = stoi(x);
	foo.erase(0, found + 1);
	found = foo.find("-");
	x = foo.substr(0, found);
	this->evpv = stoi(x);
	foo.erase(0, found + 1);
	found = foo.find("-");
	x = foo.substr(0, found);
	this->evatk = stoi(x);
	foo.erase(0, found + 1);
	found = foo.find("-");
	x = foo.substr(0, found);
	this->evdef = stoi(x);
	foo.erase(0, found + 1);
	found = foo.find("-");
	x = foo.substr(0, found);
	this->evats = stoi(x);
	foo.erase(0, found + 1);
	found = foo.find("-");
	x = foo.substr(0, found);
	this->evdes = stoi(x);
	foo.erase(0, found + 1);
	found = foo.find("-");
	x = foo.substr(0, found);
	this->evspd = stoi(x);
	foo.erase(0, found + 1);
	found = foo.find("-");
	x = foo.substr(0, found);
	this->type1 = static_cast<type>(stoi(x));
	foo.erase(0, found + 1);
	found = foo.find("-");
	x = foo.substr(0, found);
	this->type2 = static_cast<type>(stoi(x));
	foo.erase(0, found + 1);
	this->nature1 = static_cast<nature>(stoi(foo));
}

int pokemon::getGrodex()
{
	return this->pv + this->atk + this->def + this->ats + this->des + this->spd;
}

void pokemon::dexinit()
{
	pokemon::dbdex.push_back({ 1 , "bulbasaur", static_cast<type>(7) , static_cast<type>(6) });
	pokemon::dbdex.push_back({ 2 , "ivysaur", static_cast<type>(7) , static_cast<type>(6) });
	pokemon::dbdex.push_back({ 3 , "venusaur", static_cast<type>(7) , static_cast<type>(6) });
	pokemon::dbdex.push_back({ 4 , "charmander", static_cast<type>(2) , static_cast<type>(0) });
	pokemon::dbdex.push_back({ 5 , "charmeleon", static_cast<type>(2) , static_cast<type>(0) });
	pokemon::dbdex.push_back({ 6 , "charizard", static_cast<type>(5) , static_cast<type>(2) });
	pokemon::dbdex.push_back({ 7 , "squirtle", static_cast<type>(4) , static_cast<type>(0) });
	pokemon::dbdex.push_back({ 8 , "wartortle", static_cast<type>(4) , static_cast<type>(0) });
	pokemon::dbdex.push_back({ 9 , "blastoise", static_cast<type>(4) , static_cast<type>(0) });
	pokemon::dbdex.push_back({ 10 , "caterpie", static_cast<type>(13) , static_cast<type>(0) });
	pokemon::dbdex.push_back({ 11 , "metapod", static_cast<type>(13) , static_cast<type>(0) });
	pokemon::dbdex.push_back({ 12 , "butterfree", static_cast<type>(5) , static_cast<type>(13) });
	pokemon::dbdex.push_back({ 13 , "weedle", static_cast<type>(7) , static_cast<type>(13) });
	pokemon::dbdex.push_back({ 14 , "kakuna", static_cast<type>(7) , static_cast<type>(13) });
	pokemon::dbdex.push_back({ 15 , "beedrill", static_cast<type>(7) , static_cast<type>(13) });
	pokemon::dbdex.push_back({ 16 , "pidgey", static_cast<type>(5) , static_cast<type>(1) });
	pokemon::dbdex.push_back({ 17 , "pidgeotto", static_cast<type>(5) , static_cast<type>(1) });
	pokemon::dbdex.push_back({ 18 , "pidgeot", static_cast<type>(5) , static_cast<type>(1) });
	pokemon::dbdex.push_back({ 19 , "rattata", static_cast<type>(1) , static_cast<type>(0) });
	pokemon::dbdex.push_back({ 20 , "raticate", static_cast<type>(1) , static_cast<type>(0) });
	pokemon::dbdex.push_back({ 21 , "spearow", static_cast<type>(5) , static_cast<type>(1) });
	pokemon::dbdex.push_back({ 22 , "fearow", static_cast<type>(5) , static_cast<type>(1) });
	pokemon::dbdex.push_back({ 23 , "ekans", static_cast<type>(7) , static_cast<type>(0) });
	pokemon::dbdex.push_back({ 24 , "arbok", static_cast<type>(7) , static_cast<type>(0) });
	pokemon::dbdex.push_back({ 25 , "pikachu", static_cast<type>(8) , static_cast<type>(0) });
	pokemon::dbdex.push_back({ 26 , "raichu", static_cast<type>(8) , static_cast<type>(0) });
	pokemon::dbdex.push_back({ 27 , "sandshrew", static_cast<type>(9) , static_cast<type>(0) });
	pokemon::dbdex.push_back({ 28 , "sandslash", static_cast<type>(9) , static_cast<type>(0) });
	pokemon::dbdex.push_back({ 29 , "nidoran-f", static_cast<type>(7) , static_cast<type>(0) });
	pokemon::dbdex.push_back({ 30 , "nidorina", static_cast<type>(7) , static_cast<type>(0) });
	pokemon::dbdex.push_back({ 31 , "nidoqueen", static_cast<type>(9) , static_cast<type>(7) });
	pokemon::dbdex.push_back({ 32 , "nidoran-m", static_cast<type>(7) , static_cast<type>(0) });
	pokemon::dbdex.push_back({ 33 , "nidorino", static_cast<type>(7) , static_cast<type>(0) });
	pokemon::dbdex.push_back({ 34 , "nidoking", static_cast<type>(9) , static_cast<type>(7) });
	pokemon::dbdex.push_back({ 35 , "clefairy", static_cast<type>(18) , static_cast<type>(0) });
	pokemon::dbdex.push_back({ 36 , "clefable", static_cast<type>(18) , static_cast<type>(0) });
	pokemon::dbdex.push_back({ 37 , "vulpix", static_cast<type>(2) , static_cast<type>(0) });
	pokemon::dbdex.push_back({ 38 , "ninetales", static_cast<type>(2) , static_cast<type>(0) });
	pokemon::dbdex.push_back({ 39 , "jigglypuff", static_cast<type>(18) , static_cast<type>(1) });
	pokemon::dbdex.push_back({ 40 , "wigglytuff", static_cast<type>(18) , static_cast<type>(1) });
	pokemon::dbdex.push_back({ 41 , "zubat", static_cast<type>(5) , static_cast<type>(7) });
	pokemon::dbdex.push_back({ 42 , "golbat", static_cast<type>(5) , static_cast<type>(7) });
	pokemon::dbdex.push_back({ 43 , "oddish", static_cast<type>(7) , static_cast<type>(6) });
	pokemon::dbdex.push_back({ 44 , "gloom", static_cast<type>(7) , static_cast<type>(6) });
	pokemon::dbdex.push_back({ 45 , "vileplume", static_cast<type>(7) , static_cast<type>(6) });
	pokemon::dbdex.push_back({ 46 , "paras", static_cast<type>(6) , static_cast<type>(13) });
	pokemon::dbdex.push_back({ 47 , "parasect", static_cast<type>(6) , static_cast<type>(13) });
	pokemon::dbdex.push_back({ 48 , "venonat", static_cast<type>(7) , static_cast<type>(13) });
	pokemon::dbdex.push_back({ 49 , "venomoth", static_cast<type>(7) , static_cast<type>(13) });
	pokemon::dbdex.push_back({ 50 , "diglett", static_cast<type>(9) , static_cast<type>(0) });
	pokemon::dbdex.push_back({ 51 , "dugtrio", static_cast<type>(9) , static_cast<type>(0) });
	pokemon::dbdex.push_back({ 52 , "meowth", static_cast<type>(1) , static_cast<type>(0) });
	pokemon::dbdex.push_back({ 53 , "persian", static_cast<type>(1) , static_cast<type>(0) });
	pokemon::dbdex.push_back({ 54 , "psyduck", static_cast<type>(4) , static_cast<type>(0) });
	pokemon::dbdex.push_back({ 55 , "golduck", static_cast<type>(4) , static_cast<type>(0) });
	pokemon::dbdex.push_back({ 56 , "mankey", static_cast<type>(3) , static_cast<type>(0) });
	pokemon::dbdex.push_back({ 57 , "primeape", static_cast<type>(3) , static_cast<type>(0) });
	pokemon::dbdex.push_back({ 58 , "growlithe", static_cast<type>(2) , static_cast<type>(0) });
	pokemon::dbdex.push_back({ 59 , "arcanine", static_cast<type>(2) , static_cast<type>(0) });
	pokemon::dbdex.push_back({ 60 , "poliwag", static_cast<type>(4) , static_cast<type>(0) });
	pokemon::dbdex.push_back({ 61 , "poliwhirl", static_cast<type>(4) , static_cast<type>(0) });
	pokemon::dbdex.push_back({ 62 , "poliwrath", static_cast<type>(3) , static_cast<type>(4) });
	pokemon::dbdex.push_back({ 63 , "abra", static_cast<type>(10) , static_cast<type>(0) });
	pokemon::dbdex.push_back({ 64 , "kadabra", static_cast<type>(10) , static_cast<type>(0) });
	pokemon::dbdex.push_back({ 65 , "alakazam", static_cast<type>(10) , static_cast<type>(0) });
	pokemon::dbdex.push_back({ 66 , "machop", static_cast<type>(3) , static_cast<type>(0) });
	pokemon::dbdex.push_back({ 67 , "machoke", static_cast<type>(3) , static_cast<type>(0) });
	pokemon::dbdex.push_back({ 68 , "machamp", static_cast<type>(3) , static_cast<type>(0) });
	pokemon::dbdex.push_back({ 69 , "bellsprout", static_cast<type>(7) , static_cast<type>(6) });
	pokemon::dbdex.push_back({ 70 , "weepinbell", static_cast<type>(7) , static_cast<type>(6) });
	pokemon::dbdex.push_back({ 71 , "victreebel", static_cast<type>(7) , static_cast<type>(6) });
	pokemon::dbdex.push_back({ 72 , "tentacool", static_cast<type>(7) , static_cast<type>(4) });
	pokemon::dbdex.push_back({ 73 , "tentacruel", static_cast<type>(7) , static_cast<type>(4) });
	pokemon::dbdex.push_back({ 74 , "geodude", static_cast<type>(9) , static_cast<type>(11) });
	pokemon::dbdex.push_back({ 75 , "graveler", static_cast<type>(9) , static_cast<type>(11) });
	pokemon::dbdex.push_back({ 76 , "golem", static_cast<type>(9) , static_cast<type>(11) });
	pokemon::dbdex.push_back({ 77 , "ponyta", static_cast<type>(2) , static_cast<type>(0) });
	pokemon::dbdex.push_back({ 78 , "rapidash", static_cast<type>(2) , static_cast<type>(0) });
	pokemon::dbdex.push_back({ 79 , "slowpoke", static_cast<type>(10) , static_cast<type>(4) });
	pokemon::dbdex.push_back({ 80 , "slowbro", static_cast<type>(10) , static_cast<type>(4) });
	pokemon::dbdex.push_back({ 81 , "magnemite", static_cast<type>(17) , static_cast<type>(8) });
	pokemon::dbdex.push_back({ 82 , "magneton", static_cast<type>(17) , static_cast<type>(8) });
	pokemon::dbdex.push_back({ 83 , "farfetchd", static_cast<type>(5) , static_cast<type>(1) });
	pokemon::dbdex.push_back({ 84 , "doduo", static_cast<type>(5) , static_cast<type>(1) });
	pokemon::dbdex.push_back({ 85 , "dodrio", static_cast<type>(5) , static_cast<type>(1) });
	pokemon::dbdex.push_back({ 86 , "seel", static_cast<type>(4) , static_cast<type>(0) });
	pokemon::dbdex.push_back({ 87 , "dewgong", static_cast<type>(12) , static_cast<type>(4) });
	pokemon::dbdex.push_back({ 88 , "grimer", static_cast<type>(7) , static_cast<type>(0) });
	pokemon::dbdex.push_back({ 89 , "muk", static_cast<type>(7) , static_cast<type>(0) });
	pokemon::dbdex.push_back({ 90 , "shellder", static_cast<type>(4) , static_cast<type>(0) });
	pokemon::dbdex.push_back({ 91 , "cloyster", static_cast<type>(12) , static_cast<type>(4) });
	pokemon::dbdex.push_back({ 92 , "gastly", static_cast<type>(7) , static_cast<type>(15) });
	pokemon::dbdex.push_back({ 93 , "haunter", static_cast<type>(7) , static_cast<type>(15) });
	pokemon::dbdex.push_back({ 94 , "gengar", static_cast<type>(7) , static_cast<type>(15) });
	pokemon::dbdex.push_back({ 95 , "onix", static_cast<type>(9) , static_cast<type>(11) });
	pokemon::dbdex.push_back({ 96 , "drowzee", static_cast<type>(10) , static_cast<type>(0) });
	pokemon::dbdex.push_back({ 97 , "hypno", static_cast<type>(10) , static_cast<type>(0) });
	pokemon::dbdex.push_back({ 98 , "krabby", static_cast<type>(4) , static_cast<type>(0) });
	pokemon::dbdex.push_back({ 99 , "kingler", static_cast<type>(4) , static_cast<type>(0) });
	pokemon::dbdex.push_back({ 100 , "voltorb", static_cast<type>(8) , static_cast<type>(0) });
	pokemon::dbdex.push_back({ 101 , "electrode", static_cast<type>(8) , static_cast<type>(0) });
	pokemon::dbdex.push_back({ 102 , "exeggcute", static_cast<type>(10) , static_cast<type>(6) });
	pokemon::dbdex.push_back({ 103 , "exeggutor", static_cast<type>(10) , static_cast<type>(6) });
	pokemon::dbdex.push_back({ 104 , "cubone", static_cast<type>(9) , static_cast<type>(0) });
	pokemon::dbdex.push_back({ 105 , "marowak", static_cast<type>(9) , static_cast<type>(0) });
	pokemon::dbdex.push_back({ 106 , "hitmonlee", static_cast<type>(3) , static_cast<type>(0) });
	pokemon::dbdex.push_back({ 107 , "hitmonchan", static_cast<type>(3) , static_cast<type>(0) });
	pokemon::dbdex.push_back({ 108 , "lickitung", static_cast<type>(1) , static_cast<type>(0) });
	pokemon::dbdex.push_back({ 109 , "koffing", static_cast<type>(7) , static_cast<type>(0) });
	pokemon::dbdex.push_back({ 110 , "weezing", static_cast<type>(7) , static_cast<type>(0) });
	pokemon::dbdex.push_back({ 111 , "rhyhorn", static_cast<type>(11) , static_cast<type>(9) });
	pokemon::dbdex.push_back({ 112 , "rhydon", static_cast<type>(11) , static_cast<type>(9) });
	pokemon::dbdex.push_back({ 113 , "chansey", static_cast<type>(1) , static_cast<type>(0) });
	pokemon::dbdex.push_back({ 114 , "tangela", static_cast<type>(6) , static_cast<type>(0) });
	pokemon::dbdex.push_back({ 115 , "kangaskhan", static_cast<type>(1) , static_cast<type>(0) });
	pokemon::dbdex.push_back({ 116 , "horsea", static_cast<type>(4) , static_cast<type>(0) });
	pokemon::dbdex.push_back({ 117 , "seadra", static_cast<type>(4) , static_cast<type>(0) });
	pokemon::dbdex.push_back({ 118 , "goldeen", static_cast<type>(4) , static_cast<type>(0) });
	pokemon::dbdex.push_back({ 119 , "seaking", static_cast<type>(4) , static_cast<type>(0) });
	pokemon::dbdex.push_back({ 120 , "staryu", static_cast<type>(4) , static_cast<type>(0) });
	pokemon::dbdex.push_back({ 121 , "starmie", static_cast<type>(10) , static_cast<type>(4) });
	pokemon::dbdex.push_back({ 122 , "mr-mime", static_cast<type>(18) , static_cast<type>(10) });
	pokemon::dbdex.push_back({ 123 , "scyther", static_cast<type>(5) , static_cast<type>(13) });
	pokemon::dbdex.push_back({ 124 , "jynx", static_cast<type>(10) , static_cast<type>(12) });
	pokemon::dbdex.push_back({ 125 , "electabuzz", static_cast<type>(8) , static_cast<type>(0) });
	pokemon::dbdex.push_back({ 126 , "magmar", static_cast<type>(2) , static_cast<type>(0) });
	pokemon::dbdex.push_back({ 127 , "pinsir", static_cast<type>(13) , static_cast<type>(0) });
	pokemon::dbdex.push_back({ 128 , "tauros", static_cast<type>(1) , static_cast<type>(0) });
	pokemon::dbdex.push_back({ 129 , "magikarp", static_cast<type>(4) , static_cast<type>(0) });
	pokemon::dbdex.push_back({ 130 , "gyarados", static_cast<type>(5) , static_cast<type>(4) });
	pokemon::dbdex.push_back({ 131 , "lapras", static_cast<type>(12) , static_cast<type>(4) });
	pokemon::dbdex.push_back({ 132 , "ditto", static_cast<type>(1) , static_cast<type>(0) });
	pokemon::dbdex.push_back({ 133 , "eevee", static_cast<type>(1) , static_cast<type>(0) });
	pokemon::dbdex.push_back({ 134 , "vaporeon", static_cast<type>(4) , static_cast<type>(0) });
	pokemon::dbdex.push_back({ 135 , "jolteon", static_cast<type>(8) , static_cast<type>(0) });
	pokemon::dbdex.push_back({ 136 , "flareon", static_cast<type>(2) , static_cast<type>(0) });
	pokemon::dbdex.push_back({ 137 , "porygon", static_cast<type>(1) , static_cast<type>(0) });
	pokemon::dbdex.push_back({ 138 , "omanyte", static_cast<type>(4) , static_cast<type>(11) });
	pokemon::dbdex.push_back({ 139 , "omastar", static_cast<type>(4) , static_cast<type>(11) });
	pokemon::dbdex.push_back({ 140 , "kabuto", static_cast<type>(4) , static_cast<type>(11) });
	pokemon::dbdex.push_back({ 141 , "kabutops", static_cast<type>(4) , static_cast<type>(11) });
	pokemon::dbdex.push_back({ 142 , "aerodactyl", static_cast<type>(5) , static_cast<type>(11) });
	pokemon::dbdex.push_back({ 143 , "snorlax", static_cast<type>(1) , static_cast<type>(0) });
	pokemon::dbdex.push_back({ 144 , "articuno", static_cast<type>(5) , static_cast<type>(12) });
	pokemon::dbdex.push_back({ 145 , "zapdos", static_cast<type>(5) , static_cast<type>(8) });
	pokemon::dbdex.push_back({ 146 , "moltres", static_cast<type>(5) , static_cast<type>(2) });
	pokemon::dbdex.push_back({ 147 , "dratini", static_cast<type>(14) , static_cast<type>(0) });
	pokemon::dbdex.push_back({ 148 , "dragonair", static_cast<type>(14) , static_cast<type>(0) });
	pokemon::dbdex.push_back({ 149 , "dragonite", static_cast<type>(5) , static_cast<type>(14) });
	pokemon::dbdex.push_back({ 150 , "mewtwo", static_cast<type>(10) , static_cast<type>(0) });
	pokemon::dbdex.push_back({ 151 , "mew", static_cast<type>(10) , static_cast<type>(0) });
	pokemon::dbdex.push_back({ 152 , "chikorita", static_cast<type>(6) , static_cast<type>(0) });
	pokemon::dbdex.push_back({ 153 , "bayleef", static_cast<type>(6) , static_cast<type>(0) });
	pokemon::dbdex.push_back({ 154 , "meganium", static_cast<type>(6) , static_cast<type>(0) });
	pokemon::dbdex.push_back({ 155 , "cyndaquil", static_cast<type>(2) , static_cast<type>(0) });
	pokemon::dbdex.push_back({ 156 , "quilava", static_cast<type>(2) , static_cast<type>(0) });
	pokemon::dbdex.push_back({ 157 , "typhlosion", static_cast<type>(2) , static_cast<type>(0) });
	pokemon::dbdex.push_back({ 158 , "totodile", static_cast<type>(4) , static_cast<type>(0) });
	pokemon::dbdex.push_back({ 159 , "croconaw", static_cast<type>(4) , static_cast<type>(0) });
	pokemon::dbdex.push_back({ 160 , "feraligatr", static_cast<type>(4) , static_cast<type>(0) });
	pokemon::dbdex.push_back({ 161 , "sentret", static_cast<type>(1) , static_cast<type>(0) });
	pokemon::dbdex.push_back({ 162 , "furret", static_cast<type>(1) , static_cast<type>(0) });
	pokemon::dbdex.push_back({ 163 , "hoothoot", static_cast<type>(5) , static_cast<type>(1) });
	pokemon::dbdex.push_back({ 164 , "noctowl", static_cast<type>(5) , static_cast<type>(1) });
	pokemon::dbdex.push_back({ 165 , "ledyba", static_cast<type>(5) , static_cast<type>(13) });
	pokemon::dbdex.push_back({ 166 , "ledian", static_cast<type>(5) , static_cast<type>(13) });
	pokemon::dbdex.push_back({ 167 , "spinarak", static_cast<type>(7) , static_cast<type>(13) });
	pokemon::dbdex.push_back({ 168 , "ariados", static_cast<type>(7) , static_cast<type>(13) });
	pokemon::dbdex.push_back({ 169 , "crobat", static_cast<type>(5) , static_cast<type>(7) });
	pokemon::dbdex.push_back({ 170 , "chinchou", static_cast<type>(8) , static_cast<type>(4) });
	pokemon::dbdex.push_back({ 171 , "lanturn", static_cast<type>(8) , static_cast<type>(4) });
	pokemon::dbdex.push_back({ 172 , "pichu", static_cast<type>(8) , static_cast<type>(0) });
	pokemon::dbdex.push_back({ 173 , "cleffa", static_cast<type>(18) , static_cast<type>(0) });
	pokemon::dbdex.push_back({ 174 , "igglybuff", static_cast<type>(18) , static_cast<type>(1) });
	pokemon::dbdex.push_back({ 175 , "togepi", static_cast<type>(18) , static_cast<type>(0) });
	pokemon::dbdex.push_back({ 176 , "togetic", static_cast<type>(5) , static_cast<type>(18) });
	pokemon::dbdex.push_back({ 177 , "natu", static_cast<type>(5) , static_cast<type>(10) });
	pokemon::dbdex.push_back({ 178 , "xatu", static_cast<type>(5) , static_cast<type>(10) });
	pokemon::dbdex.push_back({ 179 , "mareep", static_cast<type>(8) , static_cast<type>(0) });
	pokemon::dbdex.push_back({ 180 , "flaaffy", static_cast<type>(8) , static_cast<type>(0) });
	pokemon::dbdex.push_back({ 181 , "ampharos", static_cast<type>(8) , static_cast<type>(0) });
	pokemon::dbdex.push_back({ 182 , "bellossom", static_cast<type>(6) , static_cast<type>(0) });
	pokemon::dbdex.push_back({ 183 , "marill", static_cast<type>(18) , static_cast<type>(4) });
	pokemon::dbdex.push_back({ 184 , "azumarill", static_cast<type>(18) , static_cast<type>(4) });
	pokemon::dbdex.push_back({ 185 , "sudowoodo", static_cast<type>(11) , static_cast<type>(0) });
	pokemon::dbdex.push_back({ 186 , "politoed", static_cast<type>(4) , static_cast<type>(0) });
	pokemon::dbdex.push_back({ 187 , "hoppip", static_cast<type>(5) , static_cast<type>(6) });
	pokemon::dbdex.push_back({ 188 , "skiploom", static_cast<type>(5) , static_cast<type>(6) });
	pokemon::dbdex.push_back({ 189 , "jumpluff", static_cast<type>(5) , static_cast<type>(6) });
	pokemon::dbdex.push_back({ 190 , "aipom", static_cast<type>(1) , static_cast<type>(0) });
	pokemon::dbdex.push_back({ 191 , "sunkern", static_cast<type>(6) , static_cast<type>(0) });
	pokemon::dbdex.push_back({ 192 , "sunflora", static_cast<type>(6) , static_cast<type>(0) });
	pokemon::dbdex.push_back({ 193 , "yanma", static_cast<type>(5) , static_cast<type>(13) });
	pokemon::dbdex.push_back({ 194 , "wooper", static_cast<type>(9) , static_cast<type>(4) });
	pokemon::dbdex.push_back({ 195 , "quagsire", static_cast<type>(9) , static_cast<type>(4) });
	pokemon::dbdex.push_back({ 196 , "espeon", static_cast<type>(10) , static_cast<type>(0) });
	pokemon::dbdex.push_back({ 197 , "umbreon", static_cast<type>(16) , static_cast<type>(0) });
	pokemon::dbdex.push_back({ 198 , "murkrow", static_cast<type>(5) , static_cast<type>(16) });
	pokemon::dbdex.push_back({ 199 , "slowking", static_cast<type>(10) , static_cast<type>(4) });
	pokemon::dbdex.push_back({ 200 , "misdreavus", static_cast<type>(15) , static_cast<type>(0) });
	pokemon::dbdex.push_back({ 201 , "unown", static_cast<type>(10) , static_cast<type>(0) });
	pokemon::dbdex.push_back({ 202 , "wobbuffet", static_cast<type>(10) , static_cast<type>(0) });
	pokemon::dbdex.push_back({ 203 , "girafarig", static_cast<type>(10) , static_cast<type>(1) });
	pokemon::dbdex.push_back({ 204 , "pineco", static_cast<type>(13) , static_cast<type>(0) });
	pokemon::dbdex.push_back({ 205 , "forretress", static_cast<type>(17) , static_cast<type>(13) });
	pokemon::dbdex.push_back({ 206 , "dunsparce", static_cast<type>(1) , static_cast<type>(0) });
	pokemon::dbdex.push_back({ 207 , "gligar", static_cast<type>(5) , static_cast<type>(9) });
	pokemon::dbdex.push_back({ 208 , "steelix", static_cast<type>(9) , static_cast<type>(17) });
	pokemon::dbdex.push_back({ 209 , "snubbull", static_cast<type>(18) , static_cast<type>(0) });
	pokemon::dbdex.push_back({ 210 , "granbull", static_cast<type>(18) , static_cast<type>(0) });
	pokemon::dbdex.push_back({ 211 , "qwilfish", static_cast<type>(7) , static_cast<type>(4) });
	pokemon::dbdex.push_back({ 212 , "scizor", static_cast<type>(17) , static_cast<type>(13) });
	pokemon::dbdex.push_back({ 213 , "shuckle", static_cast<type>(11) , static_cast<type>(13) });
	pokemon::dbdex.push_back({ 214 , "heracross", static_cast<type>(3) , static_cast<type>(13) });
	pokemon::dbdex.push_back({ 215 , "sneasel", static_cast<type>(12) , static_cast<type>(16) });
	pokemon::dbdex.push_back({ 216 , "teddiursa", static_cast<type>(1) , static_cast<type>(0) });
	pokemon::dbdex.push_back({ 217 , "ursaring", static_cast<type>(1) , static_cast<type>(0) });
	pokemon::dbdex.push_back({ 218 , "slugma", static_cast<type>(2) , static_cast<type>(0) });
	pokemon::dbdex.push_back({ 219 , "magcargo", static_cast<type>(11) , static_cast<type>(2) });
	pokemon::dbdex.push_back({ 220 , "swinub", static_cast<type>(9) , static_cast<type>(12) });
	pokemon::dbdex.push_back({ 221 , "piloswine", static_cast<type>(9) , static_cast<type>(12) });
	pokemon::dbdex.push_back({ 222 , "corsola", static_cast<type>(11) , static_cast<type>(4) });
	pokemon::dbdex.push_back({ 223 , "remoraid", static_cast<type>(4) , static_cast<type>(0) });
	pokemon::dbdex.push_back({ 224 , "octillery", static_cast<type>(4) , static_cast<type>(0) });
	pokemon::dbdex.push_back({ 225 , "delibird", static_cast<type>(5) , static_cast<type>(12) });
	pokemon::dbdex.push_back({ 226 , "mantine", static_cast<type>(5) , static_cast<type>(4) });
	pokemon::dbdex.push_back({ 227 , "skarmory", static_cast<type>(5) , static_cast<type>(17) });
	pokemon::dbdex.push_back({ 228 , "houndour", static_cast<type>(2) , static_cast<type>(16) });
	pokemon::dbdex.push_back({ 229 , "houndoom", static_cast<type>(2) , static_cast<type>(16) });
	pokemon::dbdex.push_back({ 230 , "kingdra", static_cast<type>(14) , static_cast<type>(4) });
	pokemon::dbdex.push_back({ 231 , "phanpy", static_cast<type>(9) , static_cast<type>(0) });
	pokemon::dbdex.push_back({ 232 , "donphan", static_cast<type>(9) , static_cast<type>(0) });
	pokemon::dbdex.push_back({ 233 , "porygon2", static_cast<type>(1) , static_cast<type>(0) });
	pokemon::dbdex.push_back({ 234 , "stantler", static_cast<type>(1) , static_cast<type>(0) });
	pokemon::dbdex.push_back({ 235 , "smeargle", static_cast<type>(1) , static_cast<type>(0) });
	pokemon::dbdex.push_back({ 236 , "tyrogue", static_cast<type>(3) , static_cast<type>(0) });
	pokemon::dbdex.push_back({ 237 , "hitmontop", static_cast<type>(3) , static_cast<type>(0) });
	pokemon::dbdex.push_back({ 238 , "smoochum", static_cast<type>(10) , static_cast<type>(12) });
	pokemon::dbdex.push_back({ 239 , "elekid", static_cast<type>(8) , static_cast<type>(0) });
	pokemon::dbdex.push_back({ 240 , "magby", static_cast<type>(2) , static_cast<type>(0) });
	pokemon::dbdex.push_back({ 241 , "miltank", static_cast<type>(1) , static_cast<type>(0) });
	pokemon::dbdex.push_back({ 242 , "blissey", static_cast<type>(1) , static_cast<type>(0) });
	pokemon::dbdex.push_back({ 243 , "raikou", static_cast<type>(8) , static_cast<type>(0) });
	pokemon::dbdex.push_back({ 244 , "entei", static_cast<type>(2) , static_cast<type>(0) });
	pokemon::dbdex.push_back({ 245 , "suicune", static_cast<type>(4) , static_cast<type>(0) });
	pokemon::dbdex.push_back({ 246 , "larvitar", static_cast<type>(9) , static_cast<type>(11) });
	pokemon::dbdex.push_back({ 247 , "pupitar", static_cast<type>(9) , static_cast<type>(11) });
	pokemon::dbdex.push_back({ 248 , "tyranitar", static_cast<type>(16) , static_cast<type>(11) });
	pokemon::dbdex.push_back({ 249 , "lugia", static_cast<type>(5) , static_cast<type>(10) });
	pokemon::dbdex.push_back({ 250 , "ho-oh", static_cast<type>(5) , static_cast<type>(2) });
	pokemon::dbdex.push_back({ 251 , "celebi", static_cast<type>(6) , static_cast<type>(10) });
	pokemon::dbdex.push_back({ 252 , "treecko", static_cast<type>(6) , static_cast<type>(0) });
	pokemon::dbdex.push_back({ 253 , "grovyle", static_cast<type>(6) , static_cast<type>(0) });
	pokemon::dbdex.push_back({ 254 , "sceptile", static_cast<type>(6) , static_cast<type>(0) });
	pokemon::dbdex.push_back({ 255 , "torchic", static_cast<type>(2) , static_cast<type>(0) });
	pokemon::dbdex.push_back({ 256 , "combusken", static_cast<type>(3) , static_cast<type>(2) });
	pokemon::dbdex.push_back({ 257 , "blaziken", static_cast<type>(3) , static_cast<type>(2) });
	pokemon::dbdex.push_back({ 258 , "mudkip", static_cast<type>(4) , static_cast<type>(0) });
	pokemon::dbdex.push_back({ 259 , "marshtomp", static_cast<type>(9) , static_cast<type>(4) });
	pokemon::dbdex.push_back({ 260 , "swampert", static_cast<type>(9) , static_cast<type>(4) });
	pokemon::dbdex.push_back({ 261 , "poochyena", static_cast<type>(16) , static_cast<type>(0) });
	pokemon::dbdex.push_back({ 262 , "mightyena", static_cast<type>(16) , static_cast<type>(0) });
	pokemon::dbdex.push_back({ 263 , "zigzagoon", static_cast<type>(1) , static_cast<type>(0) });
	pokemon::dbdex.push_back({ 264 , "linoone", static_cast<type>(1) , static_cast<type>(0) });
	pokemon::dbdex.push_back({ 265 , "wurmple", static_cast<type>(13) , static_cast<type>(0) });
	pokemon::dbdex.push_back({ 266 , "silcoon", static_cast<type>(13) , static_cast<type>(0) });
	pokemon::dbdex.push_back({ 267 , "beautifly", static_cast<type>(5) , static_cast<type>(13) });
	pokemon::dbdex.push_back({ 268 , "cascoon", static_cast<type>(13) , static_cast<type>(0) });
	pokemon::dbdex.push_back({ 269 , "dustox", static_cast<type>(7) , static_cast<type>(13) });
	pokemon::dbdex.push_back({ 270 , "lotad", static_cast<type>(6) , static_cast<type>(4) });
	pokemon::dbdex.push_back({ 271 , "lombre", static_cast<type>(6) , static_cast<type>(4) });
	pokemon::dbdex.push_back({ 272 , "ludicolo", static_cast<type>(6) , static_cast<type>(4) });
	pokemon::dbdex.push_back({ 273 , "seedot", static_cast<type>(6) , static_cast<type>(0) });
	pokemon::dbdex.push_back({ 274 , "nuzleaf", static_cast<type>(16) , static_cast<type>(6) });
	pokemon::dbdex.push_back({ 275 , "shiftry", static_cast<type>(16) , static_cast<type>(6) });
	pokemon::dbdex.push_back({ 276 , "taillow", static_cast<type>(5) , static_cast<type>(1) });
	pokemon::dbdex.push_back({ 277 , "swellow", static_cast<type>(5) , static_cast<type>(1) });
	pokemon::dbdex.push_back({ 278 , "wingull", static_cast<type>(5) , static_cast<type>(4) });
	pokemon::dbdex.push_back({ 279 , "pelipper", static_cast<type>(5) , static_cast<type>(4) });
	pokemon::dbdex.push_back({ 280 , "ralts", static_cast<type>(18) , static_cast<type>(10) });
	pokemon::dbdex.push_back({ 281 , "kirlia", static_cast<type>(18) , static_cast<type>(10) });
	pokemon::dbdex.push_back({ 282 , "gardevoir", static_cast<type>(18) , static_cast<type>(10) });
	pokemon::dbdex.push_back({ 283 , "surskit", static_cast<type>(4) , static_cast<type>(13) });
	pokemon::dbdex.push_back({ 284 , "masquerain", static_cast<type>(5) , static_cast<type>(13) });
	pokemon::dbdex.push_back({ 285 , "shroomish", static_cast<type>(6) , static_cast<type>(0) });
	pokemon::dbdex.push_back({ 286 , "breloom", static_cast<type>(3) , static_cast<type>(6) });
	pokemon::dbdex.push_back({ 287 , "slakoth", static_cast<type>(1) , static_cast<type>(0) });
	pokemon::dbdex.push_back({ 288 , "vigoroth", static_cast<type>(1) , static_cast<type>(0) });
	pokemon::dbdex.push_back({ 289 , "slaking", static_cast<type>(1) , static_cast<type>(0) });
	pokemon::dbdex.push_back({ 290 , "nincada", static_cast<type>(9) , static_cast<type>(13) });
	pokemon::dbdex.push_back({ 291 , "ninjask", static_cast<type>(5) , static_cast<type>(13) });
	pokemon::dbdex.push_back({ 292 , "shedinja", static_cast<type>(15) , static_cast<type>(13) });
	pokemon::dbdex.push_back({ 293 , "whismur", static_cast<type>(1) , static_cast<type>(0) });
	pokemon::dbdex.push_back({ 294 , "loudred", static_cast<type>(1) , static_cast<type>(0) });
	pokemon::dbdex.push_back({ 295 , "exploud", static_cast<type>(1) , static_cast<type>(0) });
	pokemon::dbdex.push_back({ 296 , "makuhita", static_cast<type>(3) , static_cast<type>(0) });
	pokemon::dbdex.push_back({ 297 , "hariyama", static_cast<type>(3) , static_cast<type>(0) });
	pokemon::dbdex.push_back({ 298 , "azurill", static_cast<type>(18) , static_cast<type>(1) });
	pokemon::dbdex.push_back({ 299 , "nosepass", static_cast<type>(11) , static_cast<type>(0) });
	pokemon::dbdex.push_back({ 300 , "skitty", static_cast<type>(1) , static_cast<type>(0) });
	pokemon::dbdex.push_back({ 301 , "delcatty", static_cast<type>(1) , static_cast<type>(0) });
	pokemon::dbdex.push_back({ 302 , "sableye", static_cast<type>(15) , static_cast<type>(16) });
	pokemon::dbdex.push_back({ 303 , "mawile", static_cast<type>(18) , static_cast<type>(17) });
	pokemon::dbdex.push_back({ 304 , "aron", static_cast<type>(11) , static_cast<type>(17) });
	pokemon::dbdex.push_back({ 305 , "lairon", static_cast<type>(11) , static_cast<type>(17) });
	pokemon::dbdex.push_back({ 306 , "aggron", static_cast<type>(11) , static_cast<type>(17) });
	pokemon::dbdex.push_back({ 307 , "meditite", static_cast<type>(10) , static_cast<type>(3) });
	pokemon::dbdex.push_back({ 308 , "medicham", static_cast<type>(10) , static_cast<type>(3) });
	pokemon::dbdex.push_back({ 309 , "electrike", static_cast<type>(8) , static_cast<type>(0) });
	pokemon::dbdex.push_back({ 310 , "manectric", static_cast<type>(8) , static_cast<type>(0) });
	pokemon::dbdex.push_back({ 311 , "plusle", static_cast<type>(8) , static_cast<type>(0) });
	pokemon::dbdex.push_back({ 312 , "minun", static_cast<type>(8) , static_cast<type>(0) });
	pokemon::dbdex.push_back({ 313 , "volbeat", static_cast<type>(13) , static_cast<type>(0) });
	pokemon::dbdex.push_back({ 314 , "illumise", static_cast<type>(13) , static_cast<type>(0) });
	pokemon::dbdex.push_back({ 315 , "roselia", static_cast<type>(7) , static_cast<type>(6) });
	pokemon::dbdex.push_back({ 316 , "gulpin", static_cast<type>(7) , static_cast<type>(0) });
	pokemon::dbdex.push_back({ 317 , "swalot", static_cast<type>(7) , static_cast<type>(0) });
	pokemon::dbdex.push_back({ 318 , "carvanha", static_cast<type>(16) , static_cast<type>(4) });
	pokemon::dbdex.push_back({ 319 , "sharpedo", static_cast<type>(16) , static_cast<type>(4) });
	pokemon::dbdex.push_back({ 320 , "wailmer", static_cast<type>(4) , static_cast<type>(0) });
	pokemon::dbdex.push_back({ 321 , "wailord", static_cast<type>(4) , static_cast<type>(0) });
	pokemon::dbdex.push_back({ 322 , "numel", static_cast<type>(9) , static_cast<type>(2) });
	pokemon::dbdex.push_back({ 323 , "camerupt", static_cast<type>(9) , static_cast<type>(2) });
	pokemon::dbdex.push_back({ 324 , "torkoal", static_cast<type>(2) , static_cast<type>(0) });
	pokemon::dbdex.push_back({ 325 , "spoink", static_cast<type>(10) , static_cast<type>(0) });
	pokemon::dbdex.push_back({ 326 , "grumpig", static_cast<type>(10) , static_cast<type>(0) });
	pokemon::dbdex.push_back({ 327 , "spinda", static_cast<type>(1) , static_cast<type>(0) });
	pokemon::dbdex.push_back({ 328 , "trapinch", static_cast<type>(9) , static_cast<type>(0) });
	pokemon::dbdex.push_back({ 329 , "vibrava", static_cast<type>(14) , static_cast<type>(9) });
	pokemon::dbdex.push_back({ 330 , "flygon", static_cast<type>(14) , static_cast<type>(9) });
	pokemon::dbdex.push_back({ 331 , "cacnea", static_cast<type>(6) , static_cast<type>(0) });
	pokemon::dbdex.push_back({ 332 , "cacturne", static_cast<type>(16) , static_cast<type>(6) });
	pokemon::dbdex.push_back({ 333 , "swablu", static_cast<type>(5) , static_cast<type>(1) });
	pokemon::dbdex.push_back({ 334 , "altaria", static_cast<type>(5) , static_cast<type>(14) });
	pokemon::dbdex.push_back({ 335 , "zangoose", static_cast<type>(1) , static_cast<type>(0) });
	pokemon::dbdex.push_back({ 336 , "seviper", static_cast<type>(7) , static_cast<type>(0) });
	pokemon::dbdex.push_back({ 337 , "lunatone", static_cast<type>(10) , static_cast<type>(11) });
	pokemon::dbdex.push_back({ 338 , "solrock", static_cast<type>(10) , static_cast<type>(11) });
	pokemon::dbdex.push_back({ 339 , "barboach", static_cast<type>(9) , static_cast<type>(4) });
	pokemon::dbdex.push_back({ 340 , "whiscash", static_cast<type>(9) , static_cast<type>(4) });
	pokemon::dbdex.push_back({ 341 , "corphish", static_cast<type>(4) , static_cast<type>(0) });
	pokemon::dbdex.push_back({ 342 , "crawdaunt", static_cast<type>(16) , static_cast<type>(4) });
	pokemon::dbdex.push_back({ 343 , "baltoy", static_cast<type>(10) , static_cast<type>(9) });
	pokemon::dbdex.push_back({ 344 , "claydol", static_cast<type>(10) , static_cast<type>(9) });
	pokemon::dbdex.push_back({ 345 , "lileep", static_cast<type>(6) , static_cast<type>(11) });
	pokemon::dbdex.push_back({ 346 , "cradily", static_cast<type>(6) , static_cast<type>(11) });
	pokemon::dbdex.push_back({ 347 , "anorith", static_cast<type>(13) , static_cast<type>(11) });
	pokemon::dbdex.push_back({ 348 , "armaldo", static_cast<type>(13) , static_cast<type>(11) });
	pokemon::dbdex.push_back({ 349 , "feebas", static_cast<type>(4) , static_cast<type>(0) });
	pokemon::dbdex.push_back({ 350 , "milotic", static_cast<type>(4) , static_cast<type>(0) });
	pokemon::dbdex.push_back({ 351 , "castform", static_cast<type>(1) , static_cast<type>(0) });
	pokemon::dbdex.push_back({ 352 , "kecleon", static_cast<type>(1) , static_cast<type>(0) });
	pokemon::dbdex.push_back({ 353 , "shuppet", static_cast<type>(15) , static_cast<type>(0) });
	pokemon::dbdex.push_back({ 354 , "banette", static_cast<type>(15) , static_cast<type>(0) });
	pokemon::dbdex.push_back({ 355 , "duskull", static_cast<type>(15) , static_cast<type>(0) });
	pokemon::dbdex.push_back({ 356 , "dusclops", static_cast<type>(15) , static_cast<type>(0) });
	pokemon::dbdex.push_back({ 357 , "tropius", static_cast<type>(5) , static_cast<type>(6) });
	pokemon::dbdex.push_back({ 358 , "chimecho", static_cast<type>(10) , static_cast<type>(0) });
	pokemon::dbdex.push_back({ 359 , "absol", static_cast<type>(16) , static_cast<type>(0) });
	pokemon::dbdex.push_back({ 360 , "wynaut", static_cast<type>(10) , static_cast<type>(0) });
	pokemon::dbdex.push_back({ 361 , "snorunt", static_cast<type>(12) , static_cast<type>(0) });
	pokemon::dbdex.push_back({ 362 , "glalie", static_cast<type>(12) , static_cast<type>(0) });
	pokemon::dbdex.push_back({ 363 , "spheal", static_cast<type>(4) , static_cast<type>(12) });
	pokemon::dbdex.push_back({ 364 , "sealeo", static_cast<type>(4) , static_cast<type>(12) });
	pokemon::dbdex.push_back({ 365 , "walrein", static_cast<type>(4) , static_cast<type>(12) });
	pokemon::dbdex.push_back({ 366 , "clamperl", static_cast<type>(4) , static_cast<type>(0) });
	pokemon::dbdex.push_back({ 367 , "huntail", static_cast<type>(4) , static_cast<type>(0) });
	pokemon::dbdex.push_back({ 368 , "gorebyss", static_cast<type>(4) , static_cast<type>(0) });
	pokemon::dbdex.push_back({ 369 , "relicanth", static_cast<type>(11) , static_cast<type>(4) });
	pokemon::dbdex.push_back({ 370 , "luvdisc", static_cast<type>(4) , static_cast<type>(0) });
	pokemon::dbdex.push_back({ 371 , "bagon", static_cast<type>(14) , static_cast<type>(0) });
	pokemon::dbdex.push_back({ 372 , "shelgon", static_cast<type>(14) , static_cast<type>(0) });
	pokemon::dbdex.push_back({ 373 , "salamence", static_cast<type>(5) , static_cast<type>(14) });
	pokemon::dbdex.push_back({ 374 , "beldum", static_cast<type>(10) , static_cast<type>(17) });
	pokemon::dbdex.push_back({ 375 , "metang", static_cast<type>(10) , static_cast<type>(17) });
	pokemon::dbdex.push_back({ 376 , "metagross", static_cast<type>(10) , static_cast<type>(17) });
	pokemon::dbdex.push_back({ 377 , "regirock", static_cast<type>(11) , static_cast<type>(0) });
	pokemon::dbdex.push_back({ 378 , "regice", static_cast<type>(12) , static_cast<type>(0) });
	pokemon::dbdex.push_back({ 379 , "registeel", static_cast<type>(17) , static_cast<type>(0) });
	pokemon::dbdex.push_back({ 380 , "latias", static_cast<type>(10) , static_cast<type>(14) });
	pokemon::dbdex.push_back({ 381 , "latios", static_cast<type>(10) , static_cast<type>(14) });
	pokemon::dbdex.push_back({ 382 , "kyogre", static_cast<type>(4) , static_cast<type>(0) });
	pokemon::dbdex.push_back({ 383 , "groudon", static_cast<type>(9) , static_cast<type>(0) });
	pokemon::dbdex.push_back({ 384 , "rayquaza", static_cast<type>(5) , static_cast<type>(14) });
	pokemon::dbdex.push_back({ 385 , "jirachi", static_cast<type>(10) , static_cast<type>(17) });
	pokemon::dbdex.push_back({ 386 , "deoxys", static_cast<type>(10) , static_cast<type>(0) });

}